### ISSUE TITLE
Broken app and unsupported usage on macOS

### ISSUE THREAD

**Issue by fralonra** [fralonra/wgshadertoy#3]
## Issues

- The app installed by dmg is unable to open directly. When open with `open -a WgShadertoy`, it displayed:
  ```
  2023-06-11 10:00:24.163 open[26824:7814785] There was an error parsing the Info.plist for the bundle at URL <0x7f94ec604c80>: NSCocoaErrorDomain - 3840
  2023-06-11 10:00:24.163 open[26824:7814785] There was an error parsing the Info.plist for the bundle at URL <0x7f94ec6064b0>: NSCocoaErrorDomain - 3840
  ```

- When try to execute the binary executable file, it crashed again:
  ```
  thread 'main' panicked at 'Error in Surface::configure: Validation Error
  
  Caused by:
      Requested usage is not supported
  ', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:734:18
  ```
  Seems that [wgpu::TextureUsages::COPY_SRC](https://github.com/fralonra/wgs/blob/a467357aab89990fd8a143e8cd9941e98e3e8fd8/crates/wgs_runtime_wgpu/src/runtime.rs#L172) is unsupported at least on this machine.

## Env

macOS 10.14.5
Radeon Pro 555X 4 GB
Intel UHD Graphics 630 1536 MB

**Comment by waimus** [comment]
I got the same error on Fedora 38, Nvidia Quadro P500, Wayland, installed via flatpak.

But I finally got it running by launching with `WGPU_BACKEND=vulkan` set.

**Comment by fralonra** [comment]
> I got the same error on Fedora 38, Nvidia Quadro P500, Wayland, installed via flatpak.
> 
> But I finally got it running by launching with `WGPU_BACKEND=vulkan` set.

Thanks for your feedback!

Might needs to switch backends for the user.

**Comment by fralonra** [comment]
After upgrading to [v0.3.2](https://github.com/fralonra/wgshadertoy/releases/tag/v0.3.2), the app will check if the `wgpu::TextureUsages::COPY_SRC` usage is supported beforehand (thanks to the newer version of `wgpu`, `egui-wgpu` and `wgs`), thus the crash would never happen again.

**Comment by fralonra** [comment]
Available on **MacPorts** from now on.

The bundling of `dmg` will be suspended until I get a Apple Developer Program account.
